#Language en-En
# Here all Strings are defined for English
ConvertFrom-StringData @'
button_folderrights = Folder Permissions
button_homerights = Home Permissions
button_PCGroups = Transfer Computergroups
button_profilerights = Profile Permissions
ChangePasswordAtLogon = You have to change the PW on first logon
CheckComputerGroups = Checking Groups of Computer
CheckConn = Check Connectivity and Basic Properties
checkHomeRights = Checking permission of home folder
checkProfileRights = Checking permission of profile folder
ComputerNotFound = Computer not found!
ComputerOfflineOrWrong = Computer offline or wrong Computername
configFolderExisting = Folder $global:Confpath is already existing
configFrom = Config from
createConfigError = Error creating the default configuration in
created = created
Cycle1 = Software Metering Usage Report Cycle
Cycle2 = User Policy Retrieval & Evaluation Cycle
Cycle3 = Machine Policy Retrieval & Evaluation Cycle
Cycle4 = File Collection Cycle
Cycle7 = Hardware Inventory Cycle
Cycle8 = Software Inventory Cycle
Cycle9 = Software Updates Deployment Evaluation Cycle
DestinationComputer = Destination-Computer
DNSConf = DNS - Configuration
DoYouWantToTransfer = Do you want to start the group transfer?
EnterCommand = Enter a command to run
EnterDestinationComputer = Enter destination Computer
EnterPassword = Enter Password
EnterSourceComputer = Enter Source Computer
EnterUsername = Enter Username
ErrorUnlocking = Error unlocking user 
existing = is already existing
FileToolStripMenuItem = File
folder = folder
FolderPathInputBoxMsg = Please enter an UNC-path.
FolderPathInputBoxTitle = Please enter an UNC-path.
FollowingLocked = The following users are locked:
groupbox11 = Network
groupbox12 = User
groupbox5 = Computergroups
groupbox6 = Permission
loaded = loaded
LockedUser = Locked User(s)
NetConf = Network - Config
noConfigFound = No config file found. You have to Configure the following Options.
NoInputDetected = No input detected
NotExistinginAD = not existing (in AD)
NoUsersLocked = No users are locked
NoUserUnlocked = No user unlocked
openPSRS = Open a PowerShell Remoting Session
OptionsToolStripMenuItem = Options
PasswordResetOK = Password reset successfully
Please = Please
PSRnotEnabled = PsRemoting does not seem to be enabled
QuitToolStripMenuItem = Quit
RegKeySet = Registry Key set. Please reboot.
RemoteCommandSent = Remote Command Sent!
RunRemoteCMD = Run a Remote Command
ShowFolderRights = Showing folder permissions.
ShowingComputergroupsOf = Showing computergroups of
ShowingLastPC = Showing last computer of the user. There may be multiple computers!
ShowLocalAdminsOf = Show local admins of
SourceComputer = Source-Computer
starting = starte
tabpage3 = Network
tabpage4 = Processes
TransferComputerGroups = Transferring computer groups. You need domain admin rights!
Transferring = Transferring
TwoIdenticalComputers = Two identical computernames
UnlockedOK = Unlocked successfully
UnlockUser = Unlock user?
YouHaveEnteredTwoIdenticalComputers = You have entered two identical computernames
'@