#Language de-DE
# Hier werden alle Strings fuer die Sprache Deutsch definiert. 
ConvertFrom-StringData @'
button_folderrights = Ordnerrechte
button_homerights = Homerechte
button_PCGroups = Computergruppen uebertragen
button_profilerights = Profilrechte
Cancel = Abbrechen
ChangePasswordAtLogon = Das Passwort muss beim ersten Anmelden geaender werden
CheckComputerGroups = Ueberpruefe die Computergruppen des Computers
CheckConn = Teste die Verbindung
checkHomeRights = Ueberpruefe Rechte des Home Laufwerks des Users
checkProfileRights = Ueberpruefe Rechte des Profilordners des Users
ComputerNotFound = Computer nicht gefunden!
ComputerOfflineOrWrong = Computer offline oder falscher Computername
configFolderExisting = Ordner $global:Confpath existiert bereits
configFrom = Konfiguration von
createConfigError = Fehler beim Erstellen der Standardkonfiguration in
created = erstellt
Cycle1 = Auswertungszyklus fuer Softwareupdatebereitstellung
Cycle2 = Benutzerrichtlinienabruf und Auswertungszyklus
Cycle3 = Computerrichtlininenabruf und Auswertungszyklus
Cycle4 = Dateisammlungszyklus
Cycle7 = Hardwareinventurzyklus
Cycle8 = Softwareinventurzyklus
Cycle9 = ueberpruefungszyklus fuer Softwareupdates
DestinationComputer = Ziel-Computer
DnsConf = DNS - Configuration
DoYouWantToTransfer = Die Computergruppenuebertragung starten?
EnterCommand = Befehl eingeben
EnterDestinationComputer = Zielcomputer eingeben
EnterPassword = Passwort eingeben
EnterSourceComputer = Quellcomputer eingeben
EnterUsername = Benutzernamen eingeben
ErrorUnlocking = Fehler beim Entsperren des Benutzers
existing = existiert bereits
FileToolStripMenuItem = Datei
folder = Ordner
FolderPathInputBoxMsg = Geben Sie einen UNC-Pfad ein.
FolderPathInputBoxTitle = Geben Sie einen UNC-Pfad ein.
FollowingLocked = Die folgenden Benutzer sind gesperrt:
General = Allgemein
groupbox11 = Netzwerk
groupbox12 = Benutzer
groupbox5 = Computergruppen
groupbox6 = Rechte
loaded = geladen
LockedUser = Gesperrte(r) User
NetConf = Netzwerkkonfiguration
noConfigFound = Keine Konfigurationsdatei gefunden. Es muessen folgende Werte konfiguriert werden.
NoInputDetected = Keine Eingabe erkannt
NotExistinginAD = existiert nicht (im AD)
NoUsersLocked = Keine Benutzer sind gesperrt
NoUserUnlocked = Kein Benutzer entsperrt
openPSRS = Starte Powershell Remotesession
OptionsToolStripMenuItem = Optionen
PasswordResetOK = Passwort erfolgreich geaendert
Please = Bitte
PSRnotEnabled = PsRemoting scheint nicht aktiviert zu sein
QuitToolStripMenuItem = Beenden
RegKeySet = Registry Key wurde gesetzt. Bitte Geraet neu starten
RemoteCommandSent = Befehl geschickt!
RunRemoteCMD = Starte einen Remote-Befehl
Save = Speichern
ShowFolderRights = Zeige rechte des Ordners
ShowingComputergroupsOf = Zeige Computergruppen von
ShowingLastPC = Zeige den letzten PC des Benutzers. Es koennen mehrere Geraete angezeigt werden!
ShowLocalAdminsOf = Anzeigen der Lokalen Admins des Computers
SourceComputer = Quell-Computer
starting = starte
tabpage3 = Netzwerk
tabpage4 = Prozesse
TransferComputerGroups = Computergruppen uebertragen. Domaenen-Admin Rechte benoetigt!
Transferring = Uebertragen
TwoIdenticalComputers = Zwei identische Computernamen
UnlockedOK = Erfolgreich entsperrt
UnlockUser = Benutzer entsperren?
YouHaveEnteredTwoIdenticalComputers = Sie haben zwei identische Computernamen eingegeben
'@